---
title: "Local Arts Data Codebook"
author: "Elena Andrews and Derex Wangmang"
date: "6/9/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Description

This is the main dataset used in this predictive modeling project. It contains data from the Local Area Arts Participation study in 1992, funded by the National Endowment for the Arts (Research Division) and conducted by Abt Associates of Cambridge, MA. There are 88 variables (note: through our pre-modeling analysis process, 22 variables were removed, and thus only 66 variables were used in the modeling process).

## Usage

`local_arts_data`

## Format

Tibble

## Variables

** next to variable means it was removed before feeding the data to the models

`caseid`** = sequential record id

`site`** = site

`abtid`** = hidden variable representing personal information about the respondent

`jazz` = has two levels, `(1) Yes` and `(2) No`, indicating whether or not respondent attended a live jazz performance in the last 12 months

`njazz` = number of times the respondent attended a live jazz concert in the last 12 months

`classic` = has two levels, `(1) Yes` and `(2) No`, indicating whether or not respondent attended a live classical music performance in the last 12 months

`nclassic` = number of times the respondent attended a live classical music concert in the last 12 months

`opera` = has two levels, `(1) Yes` and `(2) No`, indicating whether or not respondent attended a live classical music performance in the last 12 months

`nopera` = number of times the respondent attended a live opera performance in the last 12 months

`musical` = has two levels, `(1) Yes` and `(2) No`, indicating whether or not respondent attended a live musical stage performance or operetta in the last 12 months

`nmusical` = number of times the respondent attended a live musical stage performance in the last 12 months

`play` = has two levels, `(1) Yes` and `(2) No`, indicating whether or not respondent attended a live non-musical stage performance in the last 12 months

`nplay` = number of times the respondent attended a live non-musical stage performance in the last 12 months

`ballet` = has two levels, `(1) Yes` and `(2) No`, indicating whether or not respondent attended a ballet performance in the last 12 months

`nballet` = number of times the respondent attended a live ballet performance in the last 12 months

`odance` = has two levels, `(1) Yes` and `(2) No`, indicating whether or not respondent attended a live dance performance other than ballet in the last 12 months

`nodance` = number of times the respondent attended a live dance performance other than ballet in the last 12 months

`museum` = has two levels, `(1) Yes` and `(2) No`, indicating whether or not respondent visited a museum in the last 12 months

`nmuseum` = number of times the respondent visited a museum in the last 12 months

`fair` = has two levels, `(1) Yes` and `(2) No`, indicating whether or not respondent attended an art/craft fair in the last 12 months

`nfair` = number of times the respondent visited an art/craft fair in the last 12 months

`park` = has two levels, `(1) Yes` and `(2) No`, indicating whether or not respondent visited a historic park or monument or toured buildings or neighborhoods for their historic or design value in the last 12 months

`npark` = number of times the respondent visited a historic park or monument or toured buildings or neighborhoods for their historic or design value in the last 12 months

`books` = has two levels, `(1) Yes` and `(2) No`, indicating whether or not respondent read any books during the last 12 months, with the exception of books required for work or school

`nbooks` = number of books the respondent read in the last 12 months

`readplay` = has two levels, `(1) Yes` and `(2) No`, indicating whether or not respondent read any plays during the last 12 months

`readpoet` = has two levels, `(1) Yes` and `(2) No`, indicating whether or not respondent read any poetry during the last 12 months

`readnov` = has two levels, `(1) Yes` and `(2) No`, indicating whether or not respondent read any novels or short stores in the last 12 months

`hearpoet` = has two levels, `(1) Yes` and `(2) No`, indicating whether or not respondent listened to any live or recorded poetry reading in the last 12 months

`hearnov` = has two levels, `(1) Yes` and `(2) No`, indicating whether or not respondent listened to any live or recorded reading of novels or books in the last 12 months

`tvjazz` = has two levels, `(1) Yes` and `(2) No`, indicating whether or not respondent watched a jazz performance on TV or VCR in last 12 months

`ntvjazz` = number of times respondent watched a jazz performance on TV or VCR in the last 12 months

`tvclass` = has two levels, `(1) Yes` and `(2) No`, indicating whether or not respondent watched a classical music performance on TV or VCR in last 12 months

`ntvclass` = number of times respondent watched a classical music performance on TV or VCR in the last 12 months

`tvopera` = has two levels, `(1) Yes` and `(2) No`, indicating whether or not respondent watched an opera performance on TV or VCR in last 12 months

`ntvopera` = number of times respondent watched an opera performance on TV or VCR in the last 12 months

`tvmus` = has two levels, `(1) Yes` and `(2) No`, indicating whether or not respondent watched a musical stage play or operetta on TV or VCR in last 12 months

`ntvmus` = number of times respondent watched a musical stage play or operetta on TV or VCR in the last 12 months

`tvplay` = has two levels, `(1) Yes` and `(2) No`, indicating whether or not respondent watched a non-musical stage play on TV or VCR in last 12 months

`ntvplay` = number of times respondent watched a non-musical stage play on TV or VCR in the last 12 months

`tvdance` = has two levels, `(1) Yes` and `(2) No`, indicating whether or not respondent watched a dance performance, like ballet, modern, folk, or tap, on TV or VCR in last 12 months

`ntvdance` = number of times respondent watched a dance performance, like ballet, modern, folk, or tap, on TV or VCR in the last 12 months

`tvart` = has two levels, `(1) Yes` and `(2) No`, indicating whether or not respondent watched a program about artists, art works, or art museums on TV or VCR in last 12 months

`ntvart` = number of times respondent watched a program about artists, art works, or art museums on TV or VCR in the last 12 months

`lisjazz` = has two levels, `(1) Yes` and `(2) No`, indicating whether or not respondent listened to jazz performances on the radio, on records, tapes or compact disks in last 12 months

`lisclass` = has two levels, `(1) Yes` and `(2) No`, indicating whether or not respondent listened to classical music on the radio, on records, tapes or compact disks in last 12 months

`lisopera` = has two levels, `(1) Yes` and `(2) No`, indicating whether or not respondent listened to opera music on the radio, on records, tapes or compact disks in last 12 months

`lismus` = has two levels, `(1) Yes` and `(2) No`, indicating whether or not respondent listened to a musical stage play or operetta on the radio, on records, tapes or compact disks in last 12 months

`lisplay` = has two levels, `(1) Yes` and `(2) No`, indicating whether or not respondent listened to stage play on the radio, on records, tapes or compact disks in last 12 months

`cinema` = has two levels, `(1) Yes` and `(2) No`, indicating whether or not respondent went out to a movie theater to see a movie in the last 12 months

`more1` = has 8 levels, `(01) Jazz music`, `(02) Classical music`, `(03) Operas`, `(04) Musicals`, `(05) Plays`, `(06) Ballet`, `(07) Other dance`, `(08) Art museums/galleries`, indicating which kind of arts of event the participant would like to attend more frequently

`more2` = has 8 levels, `(01) Jazz music`, `(02) Classical music`, `(03) Operas`, `(04) Musicals`, `(05) Plays`, `(06) Ballet`, `(07) Other dance`, `(08) Art museums/galleries`, indicating which kind of arts of event the participant would like to attend more frequently (second answer)

`more3`** = has 8 levels, `(01) Jazz music`, `(02) Classical music`, `(03) Operas`, `(04) Musicals`, `(05) Plays`, `(06) Ballet`, `(07) Other dance`, `(08) Art museums/galleries`, indicating which kind of arts of event the participant would like to attend more frequently (third answer)

`more4`** = has 8 levels, `(01) Jazz music`, `(02) Classical music`, `(03) Operas`, `(04) Musicals`, `(05) Plays`, `(06) Ballet`, `(07) Other dance`, `(08) Art museums/galleries`, indicating which kind of arts of event the participant would like to attend more frequently (fourth answer)

`more5`** = has 8 levels, `(01) Jazz music`, `(02) Classical music`, `(03) Operas`, `(04) Musicals`, `(05) Plays`, `(06) Ballet`, `(07) Other dance`, `(08) Art museums/galleries`, indicating which kind of arts of event the participant would like to attend more frequently (fifth answer)

`more6`** = has 8 levels, `(01) Jazz music`, `(02) Classical music`, `(03) Operas`, `(04) Musicals`, `(05) Plays`, `(06) Ballet`, `(07) Other dance`, `(08) Art museums/galleries`, indicating which kind of arts of event the participant would like to attend more frequently (sixth answer)

`more7`** = has 8 levels, `(01) Jazz music`, `(02) Classical music`, `(03) Operas`, `(04) Musicals`, `(05) Plays`, `(06) Ballet`, `(07) Other dance`, `(08) Art museums/galleries`, indicating which kind of arts of event the participant would like to attend more frequently (seventh answer)

`more8`** = has 8 levels, `(01) Jazz music`, `(02) Classical music`, `(03) Operas`, `(04) Musicals`, `(05) Plays`, `(06) Ballet`, `(07) Other dance`, `(08) Art museums/galleries`, indicating which kind of arts of event the participant would like to attend more frequently (eight answer)

`moremost` = has 8 levels, `(01) Jazz music`, `(02) Classical music`, `(03) Operas`, `(04) Musicals`, `(05) Plays`, `(06) Ballet`, `(07) Other dance`, `(08) Art museums/galleries`, indicating which kind of arts of event the participant would MOST like to attend more frequently

`gomore` = has two levels, `(1) Yes` and `(2) No`, indicating whether or not respondent would, in general, like to attend cultural and artistic events more often than they have in the last 12 months

`bar1` = has 17 levels, `(01) Lack of interest`, `(02) Don't have time`, `(03) Cost of tickets`, `(04) Overall cost`, `(05) Tickets sold out`, `(06) Transportation/traffic/parking`, `(07) Distance/travel time`, `(08) Crime`, `(09) Lack of child care`, `(10) Poor quality of performance`, `(11) Not available/no variety`, `(12) No one to go with`, `(13) Handicap problem`, `(14) Age problem`,  `(15) Prefer to watch TV`, `(16) Just don't get around to it`, `(95) Other`, indicating the reason the respondent did not attend arts events more often (first answer)

`bar2`** = has 17 levels, `(01) Lack of interest`, `(02) Don't have time`, `(03) Cost of tickets`, `(04) Overall cost`, `(05) Tickets sold out`, `(06) Transportation/traffic/parking`, `(07) Distance/travel time`, `(08) Crime`, `(09) Lack of child care`, `(10) Poor quality of performance`, `(11) Not available/no variety`, `(12) No one to go with`, `(13) Handicap problem`, `(14) Age problem`,  `(15) Prefer to watch TV`, `(16) Just don't get around to it`, `(95) Other`, indicating the reason the respondent did not attend arts events more often (second answer)

`bar3`** = has 17 levels, `(01) Lack of interest`, `(02) Don't have time`, `(03) Cost of tickets`, `(04) Overall cost`, `(05) Tickets sold out`, `(06) Transportation/traffic/parking`, `(07) Distance/travel time`, `(08) Crime`, `(09) Lack of child care`, `(10) Poor quality of performance`, `(11) Not available/no variety`, `(12) No one to go with`, `(13) Handicap problem`, `(14) Age problem`,  `(15) Prefer to watch TV`, `(16) Just don't get around to it`, `(95) Other`, indicating the reason the respondent did not attend arts events more often (third answer)

`bar4`** = has 17 levels, `(01) Lack of interest`, `(02) Don't have time`, `(03) Cost of tickets`, `(04) Overall cost`, `(05) Tickets sold out`, `(06) Transportation/traffic/parking`, `(07) Distance/travel time`, `(08) Crime`, `(09) Lack of child care`, `(10) Poor quality of performance`, `(11) Not available/no variety`, `(12) No one to go with`, `(13) Handicap problem`, `(14) Age problem`,  `(15) Prefer to watch TV`, `(16) Just don't get around to it`, `(95) Other`, indicating the reason the respondent did not attend arts events more often (fourth answer)

`bar5`** = has 17 levels, `(01) Lack of interest`, `(02) Don't have time`, `(03) Cost of tickets`, `(04) Overall cost`, `(05) Tickets sold out`, `(06) Transportation/traffic/parking`, `(07) Distance/travel time`, `(08) Crime`, `(09) Lack of child care`, `(10) Poor quality of performance`, `(11) Not available/no variety`, `(12) No one to go with`, `(13) Handicap problem`, `(14) Age problem`,  `(15) Prefer to watch TV`, `(16) Just don't get around to it`, `(95) Other`, indicating the reason the respondent did not attend arts events more often (fifth answer)

`mostimp` = has 18 levels, `(02) Lack of interest`, `(03) Don't have time`, `(04) Cost of tickets`, `(05) Overall cost`, `(06) Tickets sold out`, `(07) Transportation/traffic/parking`, `(08) Distance/travel time`, `(09) Crime`, `(10) Lack of child care`, `(11) Poor quality of performance`, `(12) Not available/no variety`, `(13) No one to go with`, `(14) Handicap problem`, `(15) Age problem`,  `(16) Prefer to watch TV`, `(17) Just don't get around to it`, `(18) Not enough info on events`, `(95) Other`, indicating the respondent's most important reason for not attending more arts events

`howimp` = has 3 levels, `(1) Very important`, `(2) Somewhat important`, `(3) Not at all important`, indicating how important the respondent feels it is to attend/take part in arts activities and events

`schools` = has 3 levels, `(1) Very important`, `(2) Somewhat important`, `(3) Not at all important`, indicating how important the respondent feels it is to to offer activities such as music, dance, theater, and art in schools

`source1` = has 11 levels, `(01) Newspapers`, `(02) Word of mouth`, `(03) Friends/relatives/others`, `(04) Direct mail`, `(05) Posters/notices`, `(06) Television`, `(07) Radio`, `(08) Magazines`, `(09) School notices`, `(10) Telemarketing`, `(95) Other` indicating how the respondent learned about arts events in their community

`source2`** = has 12 levels, `(00) 0`, `(01) Newspapers`, `(02) Word of mouth`, `(03) Friends/relatives/others`, `(04) Direct mail`, `(05) Posters/notices`, `(06) Television`, `(07) Radio`, `(08) Magazines`, `(09) School notices`, `(10) Telemarketing`, `(95) Other` indicating how the respondent learned about arts events in their community (second answer)

`source3`** = has 12 levels, `(00) 0`, `(01) Newspapers`, `(02) Word of mouth`, `(03) Friends/relatives/others`, `(04) Direct mail`, `(05) Posters/notices`, `(06) Television`, `(07) Radio`, `(08) Magazines`, `(09) School notices`, `(10) Telemarketing`, `(95) Other` indicating how the respondent learned about arts events in their community (third answer)

`source4`** = has 12 levels, `(00) 0`, `(01) Newspapers`, `(02) Word of mouth`, `(03) Friends/relatives/others`, `(04) Direct mail`, `(05) Posters/notices`, `(06) Television`, `(07) Radio`, `(08) Magazines`, `(09) School notices`, `(10) Telemarketing`, `(95) Other` indicating how the respondent learned about arts events in their community (fourth answer)

`source5`** = has 12 levels, `(00) 0`, `(01) Newspapers`, `(02) Word of mouth`, `(03) Friends/relatives/others`, `(04) Direct mail`, `(05) Posters/notices`, `(06) Television`, `(07) Radio`, `(08) Magazines`, `(09) School notices`, `(10) Telemarketing`, `(95) Other` indicating how the respondent learned about arts events in their community (fifth answer)

`newsp`** = has 4 levels, `(01) Verbatim answer recorded`, `(97) None`, `(98) Don't know`, `(99) Refused`, indicating which newspapers (if any) the respondent learned about arts events from

`tvtype`** = has 5 levels, `(1) Cable TV`, `(2) Network TV`, `(3) Both`, `(4) Don't know`, `(5) Refused`, indicating what kind of tv the respondent learned about arts events from 

`radio`** = has 4 levels, `(01) Verbatim answer recorded`, `(97) None`, `(98) Don't know`, `(99) Refused`, indicating which radio stations (if any) the respondent learned about arts events from

`mags`** = has 4 levels, `(01) Verbatim answer recorded`, `(97) None`, `(98) Don't know`, `(99) Refused`, indicating which magazines (if any) the respondent learned about arts events from

`rateinfo` = has 4 levels, `(1) Excellent`, `(2) Good`, `(3) Fair`, `(4) Poor`, indicating how the respondent would rate the availability and adequacy of information about arts events in their area

`hhsize` = number of people in respondent's household

`over18` = number of people in respondent's household that are 18 years old or older

`age` = age of respondent

`marital` = has 5 levels, `(1) Married`, `(2) Widowed`, `(3) Separated`, `(4) Divorced`, `(5) Never married`, indicating the martial status of the respondent

`educ` = has 10 levels, `(01) No school`, `(02) Grades k-8`, `(03) Grades 9-11`, `(04) High school`, `(05) Vocational school`, `(06) Some college`, `(07) Bachelors degree`,  `(08) Some grad. school`, `(09) Grad. degree`, `(95) Other`, indicating the highest grade of school or highest degree the respondent has completed

`race` = has 10 levels, `(01) White, not Hispanic`, `(02) Black`, `(03) Hispanic/Latino`, `(04) Carribean`, `(05) Central American`, `(06) South American`, `(07) Native American`, `(08) Alaskan Native`, `(09) Asian/Pacific Islander/Filipino`,
`(95) Other`, indicating the respondent's name

`income` = has 9 levels, `Under $10,000`, `$10,000 to $14,999`, `$15,000 to $19,999`, `$20,000 to $29,999`, `$30,000 to $39,999`, `$40,000 to $49,999`, `$50,000 to $74,999`, `$75,000 to $99,999`, `$100,000 or more`, indicating the respondent's household income in 1991

`gender` = has 2 levels, `(1) Male`, `(2) Female`, indicating the respondent's gender

`weight` = weighing factor

`exchange`** = hidden variable representing the 3-digit exchange of the respondent
