---
title: "Data Memo"
author: "Derex Wangmang and Elena Andrews"
date: "April 7, 2021"
output:
  html_document:
    toc: true
    toc_float: true
    highlight: "tango"
  pdf_document:
    latex_engine: xelatex
---

## Overview

The data-set we will be using for our final project comes from the Local Area Arts Participation study from 1992. This study was funded by the National Endowment for the Arts (Research Division) and conducted by Abt Associates of Cambridge, MA. It contains information on whether and how often Americans attend and participate in various kinds of local art (such as live jazz, musicals, ballets, operas, and museums). The study also includes demographic information about the respondents, including age, education level, income level, gender, and race. 5,040 total Americans from 12 different localities (Broward County, Chicago, Dade County, Las Vegas, Pittsburgh, Reno, Rural Nevada, San Jose, Seattle, Sedona, Winston-Salem) were randomly selected via a random-digit-dialing sampling methodology and contacted by phone for this survey. We have already downloaded the data as a .rda file from the NADAC (National Archive of Data on Arts and Culture) website.

**Link to NADAC site containing the data:** <https://www.icpsr.umich.edu/web/NADAC/studies/35586>

**Citation Provided for Data:** National Endowment for the Arts. Local Area Arts Participation Study 1992. Ann Arbor, MI: Inter-university Consortium for Political and Social Research [distributor], 2015-03-23. <https://doi.org/10.3886/ICPSR35586.v1>

The dataset contains 5,040 observations and 95 variables. The majority of the variables are categorical variables, as many of the survey questions ask whether or not the respondent has been to a specific type of art venue or performance in the last year. There are some numeric variables, though, as well. As delineated below, there are some variables with quite a bit of missingness, but this is because the variable represents a survey question that is conditional on a previous question, and doesn't apply to those who responded a certain way to that previous question. This is typical of survey data. We do not need to join multiple data-sets together.

## Research Questions

Our project will be focused on a predictive analysis. Potential research questions include:

-   Based on some or all of the factors, how often would a given participant attend different performances?
-   Based on some or all of the factors, what is the age of the participant?
-   Based on some or all of the factors, what is the income range for the participant?

Of these, predicting the income range is the most similar to a real world scenario. Thus, we will most likely focus on answering that question. Since this is an income range, rather than income itself, this question may be best answered by a classification approach.

Variables that may be helpful in modeling the response may include the education level, age, and participation in arts and performances.

## Expected Data Difficulties

The data retrieval process consisted of downloading the dataset from an online resource.

Many rows contain `NA` values, but that is most likely due to the fact that some values are conditional on the answers to other columns. For example, the fourth column is about whether the participant attended a live jazz performance, while fifth column is about how many *times* the participant attended a live jazz performance in the last 12 months. Thus those people who responded that they didn't attend a live jazz performance in last 12 months wouldn't have any response to the number of times they attended a live jazz performance (resulting in missing values). There are 4188 `No` responses and 9 `Don't know` responses in the fourth column and 4197 `NA` responses in the fifth column. This confirms that missing values in the fifth column correspond to people who said `No` or `Don't know` to question four (whether or not they attended live jazz in the past year). In fact, in these cases, these missing values should really be zeros, and thus may have to be changed manually. In other cases, however, the data may simply be missing, or the participant might have felt uncomfortable answering the question.

Other minor difficulties may come from data cleaning that needs to take place before the data can be used in the modeling process. The data unfortunately does not come in a tibble format, and therefore must be converted. The variable names should also be cleaned so that they are all in snake case. Finally, the factor variables might have to be edited. Although they all accurately read in as factor variables, the levels of all the factor variables include numbers as well as text (for example, the variable `jazz` has the levels `(1) Yes`, `(2) No`, `(3) Don't Know`, and `(4) Refused`). This data cleaning is relatively minor, however, and shouldn't pose any major problems.

## Proposed Timeline

We have already created a Github repo and connected R project for the final project, containing the unprocessed dataset and this data memo. Below is a timeline for the rest of the project steps.

**April 5th-11th:** Complete necessary data cleaning steps. Finalize outcome variable for project. Split the data into a training and testing set, stratifying based on outcome variable. Begin conducting an exploratory data analysis on the data-set.

**April 12th-21st:** Finish exploratory data-analysis. Begin feature engineering, considering what pre-processing steps would make most sense based on what was learned from the EDA.

**April 21st-May 2nd:** Finish feature engineering and constructing recipes.

**May 3rd-May 9th:** Choose types of models to use, construct models and their workflows, and choose which parameters to tune. Begin tuning models.

**May 10th-May 16th:** Work on tuning models, troubleshooting if necessary.

**May 17th-May 23rd:** Evaluate models, choose a model that performs the best, and apply to testing data.

**May 24th-June 9th:** Finish any necessary aspects of the project, including troubleshooting any remaining problems with models, finishing the project write-up, and completing the executive summary.
